# Generated by Django 6.0.2 on 2026-04-03 12:59
# Data migration: backfill Patient.user FK from existing PATIENT users.

from django.db import migrations


def backfill_patient_user_fk(apps, schema_editor):
    Patient = apps.get_model('patients', 'Patient')
    CustomUser = apps.get_model('accounts', 'CustomUser')

    patient_users = CustomUser.objects.filter(role='PATIENT')
    for user in patient_users:
        # Try email match first, then phone match
        patient = None
        if user.email:
            patient = Patient.objects.filter(email__iexact=user.email, user__isnull=True).first()
        if not patient and user.phone_number:
            patient = Patient.objects.filter(contact_number=user.phone_number, user__isnull=True).first()
        if patient:
            patient.user = user
            patient.save(update_fields=['user'])


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_add_user_fk_visit_labreport'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_patient_user_fk, migrations.RunPython.noop),
    ]
