# Generated by Django 6.0.1 on 2026-04-05 07:21

import datetime
import django.db.models.deletion
import patients.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_backfill_user_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labreport',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Lab Report', 'verbose_name_plural': 'Lab Reports'},
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='file',
        ),
        migrations.RemoveField(
            model_name='labreport',
            name='title',
        ),
        migrations.AddField(
            model_name='labreport',
            name='pdf_file',
            field=models.FileField(default='', help_text='Upload the lab report PDF (max 5 MB).', upload_to='lab_reports/%Y/%m/', validators=[patients.models._validate_lab_report_pdf]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_date',
            field=models.DateField(default=datetime.date(2026, 4, 5), help_text='Date the test was conducted.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='labreport',
            name='test_name',
            field=models.CharField(default='', help_text='Name of the lab test (e.g. CBC, Lipid Panel).', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_lab_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
