# Generated by Django 6.0.2 on 2026-04-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, help_text='For doctors (e.g., Cardiology, General Practice)', max_length=100, null=True),
        ),
    ]
