# Generated by Django 6.0.1 on 2026-04-05 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorunavailability'),
        ('patients', '0003_backfill_user_fk'),
        ('prescriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='notes',
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(blank=True, help_text='The clinical visit during which this prescription was issued.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.visit'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescription', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions_written', to=settings.AUTH_USER_MODEL),
        ),
    ]
