# Generated by Django 6.0.1 on 2026-04-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_add_visit_fk_remove_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='dispense_status',
            field=models.CharField(choices=[('PENDING', 'Pending Dispense'), ('DISPENSED', 'Dispensed')], db_index=True, default='PENDING', help_text='Tracks whether the pharmacist has dispensed medicines.', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
