# Generated by Django 6.0.2 on 2026-04-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Common name of the medicine', max_length=255, unique=True)),
                ('default_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional descriptions or default instructions', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='due_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item_type',
            field=models.CharField(choices=[('CONSULTATION', 'Consultation'), ('MEDICINE', 'Medicine'), ('LAB', 'Lab / Test'), ('PROCEDURE', 'Procedure / Service'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='notes',
            field=models.CharField(blank=True, help_text='Optional dosage or details', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded / Cancelled')], default='UNPAID', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='service_name',
            field=models.CharField(help_text='e.g., General Consultation, Paracetamol', max_length=255),
        ),
    ]
