# Generated by Django 6.0.1 on 2026-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_medicinemaster_invoice_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('REFUNDED', 'Refunded / Cancelled')], default='UNPAID', max_length=20),
        ),
    ]
