# Generated by Django 6.0.2 on 2026-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_add_rescheduled_status_cancellation_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Checked In'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('NOSHOW', 'No Show'), ('RESCHEDULED', 'Rescheduled')], db_index=True, default='SCHEDULED', max_length=20),
        ),
    ]
