# Generated by Django 6.0.2 on 2026-04-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='room_assignment',
            field=models.CharField(blank=True, help_text='Room assigned during check-in', max_length=50, null=True),
        ),
    ]
