# Generated by Django 6.0.1 on 2026-04-05 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='publication',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of approval.', null=True),
        ),
        migrations.AddField(
            model_name='publication',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin/staff who approved this paper.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publication',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the doctor on rejection.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='admin_notes',
            field=models.TextField(blank=True, help_text='Internal notes from the reviewer.'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.CharField(help_text='Comma-separated list of authors.', max_length=500),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=20),
        ),
    ]
